name: google_maps_places_autocomplete_widgets
description: TextField and TextFormField widgets using Google Maps Places Api for Address Autocompletion.
version: 1.2.3

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
